# 配置普通静态资源的path patter
# spring.mvc.static-path-pattern=/**
# 配置普通静态资源文件存储位置
# spring.web.resources.static-locations=classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/

# 配置普通静态资源的path patter
#spring.mvc.static-path-pattern=/george/**
# 配置普通静态资源文件存储位置
#spring.web.resources.static-locations=classpath:/george/



# 静态资源缓存设置
# 1. 缓存有效期
spring.web.resources.cache.period=100
# 2. 缓存控制（Cache Control配置的话，period会失效）
spring.web.resources.cache.cachecontrol.max-age=20
# 3. 是否使用缓存的最后修改时间（默认是：使用）
spring.web.resources.cache.use-last-modified=true
# 4. 是否开启静态资源默认处理方式（默认是：开启）
spring.web.resources.add-mappings=true